#database.url=jdbc:postgresql://localhost:5434/monitoring_service_db
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5434/monitoring_service_db
    url: jdbc:postgresql://postgres:5432/monitoring_service_db
    username: ylab_user
    password: ylab_password
  liquibase:
    default-schema: monitoring_service_schema
    service-schema: data_changelog_schema
    change-log: classpath:db/changelog/changelog-master.xml

