version: '3'
services:
  postgres:
    image: postgres:12.3
    container_name: monitoring_service_database
    ports:
      - 5434:5432
    restart: on-failure
    environment:
      POSTGRES_USER: ylab_user
      POSTGRES_PASSWORD: ylab_password
      POSTGRES_DB: monitoring_service_db
  tomcat:
    container_name: tomcat
    image: tomcat:10.0
    ports:
      - "8080:8080"
    volumes:
      - ./target/monitoring-service.war:/usr/local/tomcat/webapps/monitoring-service.war
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
  frontend:
    container_name: frontend
    image: dimatch86/monitoring-service
    ports:
      - "8081:8080"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s