version: '3'
services:
  postgres:
    image: postgres:12.3
    container_name: monitoring_service_database
    ports:
      - 5434:5432
    restart: on-failure
    environment:
      POSTGRES_USER: ylab_user
      POSTGRES_PASSWORD: ylab_password
      POSTGRES_DB: monitoring_service_db